PROMPT Dropping user ccm

    DROP USER ccm CASCADE;

PROMPT Creating user ccm

    CREATE USER ccm
    IDENTIFIED BY ccm
    DEFAULT TABLESPACE ccm
    TEMPORARY TABLESPACE TEMP PROFILE DEFAULT
    QUOTA UNLIMITED ON ccm
    QUOTA 0 ON USERS;

    GRANT CONNECT, RESOURCE, QUERY REWRITE, CTXAPP, CREATE PROCEDURE, CREATE TRIGGER, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO ccm;

    REVOKE UNLIMITED TABLESPACE FROM ccm;

    REVOKE RESOURCE FROM ccm;
	
QUIT;
