PROMPT Dropping USER ccm

    DROP USER ccm CASCADE;

PROMPT Creating USER ccm

    CREATE USER ccm
    IDENTIFIED BY ccm
    DEFAULT TABLESPACE APLAWS
    TEMPORARY TABLESPACE TEMP PROFILE DEFAULT
    QUOTA UNLIMITED ON APLAWS
    QUOTA 0 ON USERS;

    GRANT CONNECT, RESOURCE, QUERY REWRITE, CTXAPP, CREATE PROCEDURE, CREATE TRIGGER, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO ccm;

    REVOKE UNLIMITED TABLESPACE FROM ccm;

    REVOKE RESOURCE FROM ccm;
	
QUIT;
