/*
 * Copyright (C) 2003-2004 Red Hat Inc. All Rights Reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 */
package com.arsdigita.search.lucene;


import org.apache.lucene.search.Filter;
import org.apache.lucene.index.IndexReader;

import java.util.BitSet;
import java.io.IOException;

import org.apache.log4j.Logger;


/**
 * A filter whose bitset is the logical
 * NOT of the bitset generated by the
 * wrapped filter.
 */
public class NegationFilter extends Filter {

    private static final Logger s_log = 
        Logger.getLogger(NegationFilter.class);
    
    private Filter m_filter;
    
    public NegationFilter(Filter filter) {
        m_filter = filter;
    }
    
    /**
     * @return bitset for the negation of the wrapped filter
     */
    public BitSet bits(IndexReader reader)
        throws IOException {
        
        BitSet bits = new BitSet(reader.maxDoc());
        if (s_log.isDebugEnabled()) {
            s_log.debug("Adding filter " + m_filter.getClass());
        }
        bits.xor(m_filter.bits(reader));
        return bits;
    }
}
