// Red Hat Enterprise Portal Server initialization file
//
// When running Portal Server, the parameters for
// com.arsdigita.kernel.Initializer must be modified.
//
// ::login-stylesheet:: -> login_ps_en.xsl
// ::subsite-dispatcher-class:: -> com.arsdigita.portalserver.pslogin.PSSubsiteDispatcher


// The following inits are the old way to initialize applications
// and are going to be replaced by new style initializers.
init com.arsdigita.portalserver.OldInitializer { }

init com.arsdigita.portalserver.admin.Initializer { }

init com.arsdigita.portalserver.ui.admin.Initializer { }

init com.arsdigita.portalserver.personal.Initializer { }


// The populate code is ot not any use in a production environment
// but only for testing.

// init com.arsdigita.populate.portalserver.Initializer {
//     //Set baseStringSeed to a non-empty value 
//     //to make all generated Strings in params
//     //deterministic rather than random.  This will
//     //allow you to populate the same values across
//     //multiple runs on clean databases.
//     baseStringSeed = "";
//     numUsers = 5;
//     numPortalSiteLevels = 2;
//     numPortalSitesPerLevel = 2;
//     populateAppPairs = {
//  	//populateForum args: numPosts, numMsgs per post
//  	{ "com.arsdigita.forum.PopulateForum", {3, 5}},
//  	//populateDocmgr args: numFolderLevels, numFolders, numFiles
// 	{ "com.arsdigita.docmgr.PopulateDocmgr", {3, 2, 2}},
//  	//populateFaq args: numQuestions
//  	{ "com.arsdigita.faq.PopulateFaq", {5}},
//  	//populateGlossary args: numWords
//  	{ "com.arsdigita.glossary.PopulateGlossary", {5}},
//  	//populateBookmarks args: numBookmarks
//  	{ "com.arsdigita.bookmarks.PopulateBookmarks", {5}}
//     };
//     populatePortlets = {
// 	"com.arsdigita.portlets.freeform.PopulateFreeformPortlet",
// 	"com.arsdigita.portlets.timeofday.PopulateTimeOfDayPortlet",
// 	"com.arsdigita.portlets.rssfeed.PopulateRSSFeedPortlet",
// 	"com.arsdigita.populate.portlets.PopulateApplicationDirectoryPortlet",
// 	"com.arsdigita.populate.portlets.PopulatePortalNavigatorPortlet",
// 	"com.arsdigita.populate.portlets.PopulatePortalSummaryPortlet",
// 	"com.arsdigita.populate.portlets.PopulateMyPortalsPortlet"
//     };
// }
