/*
 * Copyright (C) 2003-2004 Red Hat Inc. All Rights Reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 */
package com.arsdigita.packaging;

import com.arsdigita.runtime.ConfigRegistry;
import com.arsdigita.runtime.CCMResourceManager;
import com.arsdigita.util.Classes;
import com.arsdigita.util.JavaPropertyWriter;
import com.arsdigita.util.parameter.ErrorList;
import com.arsdigita.util.parameter.ParameterContext;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintStream;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Properties;

/**
 * PackageTool helper class: Writes a config database to its physical storage
 * in file system.
 *
 * Used by some command worker classes of the packaging package, which handle
 * configuration tasks, esp. the "load", "clear", "set" and "get" commands.
 * 
 * This class is <strong>not</strong> supported API.
 *
 * @author Rafael H. Schloming &lt;rhs@mit.edu&gt;
 * @version $Revision: #7 $ $Date: 2004/08/16 $
 * @version $Id: Config.java 736 2005-09-01 10:46:05Z sskracic $
 **/

public final class Config extends ParameterMap {

    private ConfigRegistry m_reg;

    /**
     * Constructor, creates an Config object
     * @param reg
     **/
    public Config(ConfigRegistry reg) {
        m_reg = reg;

        for (Iterator it = m_reg.getContexts().iterator(); it.hasNext(); ) {
            Class klass = (Class) it.next();
            ParameterContext context =
                (ParameterContext) Classes.newInstance(klass);
            addContext(context);
        }
    }

    /**
     * 
     * @param errs
     **/
    void load(ErrorList errs) {
        for (Iterator it = getContexts().iterator(); it.hasNext(); ) {
            ParameterContext ctx = (ParameterContext) it.next();
            m_reg.load(ctx, errs);
        }
    }

    public final boolean load(PrintStream out) {
        ErrorList errs = new ErrorList();
        load(errs);
        if (!errs.isEmpty()) {
            out.println(" *** Warning ***");
            errs.report(new OutputStreamWriter(out));
            return false;
        }

        return true;
    }

    public final void save() throws IOException {
        save(CCMResourceManager.getConfigDirectory());
    }

    /**
     * Write the config parameter to the file system.
     * 
     * @param confDir full path of the config directory location in the file system
     * @throws java.io.IOException
     **/
    void save(File confDir) throws IOException {
        if (!confDir.exists()) {
            throw new IOException("no such directory: " + confDir);
        }

        if (confDir.isFile()) {
            throw new IOException("expecting directory: " + confDir);
        }

        if (!confDir.canWrite()) {
            throw new IOException("cannot write to directory: " + confDir);
        }

        HashMap stores = new HashMap();
        for (Iterator it = getContexts().iterator(); it.hasNext(); ) {
            ParameterContext ctx = (ParameterContext) it.next();
            String storage = m_reg.getStorage(ctx.getClass());
            Properties props = (Properties) stores.get(storage);
            if (props == null) {
                props = new Properties();
                stores.put(storage, props);
            }

            ctx.save(new JavaPropertyWriter(props));
        }

        for (Iterator it = stores.entrySet().iterator(); it.hasNext(); ) {
            Map.Entry me = (Map.Entry) it.next();
            String storage = (String) me.getKey();
            Properties props = (Properties) me.getValue();
            if (props.size() == 0) { continue; }
            File file = new File(confDir, storage);
            File dir = file.getParentFile();
            dir.mkdirs();
            if (!(dir.exists() && dir.isDirectory())) {
                throw new IOException("unable to create directory: " + dir);
            }
            try {
                FileOutputStream out = new FileOutputStream(file);
                props.store
                    (out, " Generated by " + getClass().getName());
                out.close();
            } catch (IOException e) {
                throw new IOException
                    ("unable to save file: " + e.getMessage());
            }
        }
    }

}
