--
-- Copyright (C) 2003-2004 Red Hat Inc. All Rights Reserved.
--
-- This library is free software; you can redistribute it and/or
-- modify it under the terms of the GNU Lesser General Public License
-- as published by the Free Software Foundation; either version 2.1 of
-- the License, or (at your option) any later version.
--
-- This library is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
-- Lesser General Public License for more details.
--
-- You should have received a copy of the GNU Lesser General Public
-- License along with this library; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
--
-- $Id: insert-iso-countries.sql 1597 2007-07-10 16:27:26Z p_boy $
-- $DateTime: 2004/08/17 23:15:09 $
insert into iso_countries (iso_code, country_name) values ('AF', 'Afghanistan');
insert into iso_countries (iso_code, country_name) values ('AL', 'Albania');
insert into iso_countries (iso_code, country_name) values ('DZ', 'Algeria');
insert into iso_countries (iso_code, country_name) values ('AS', 'American Samoa');
insert into iso_countries (iso_code, country_name) values ('AD', 'andorra');
insert into iso_countries (iso_code, country_name) values ('AO', 'Angola');
insert into iso_countries (iso_code, country_name) values ('AI', 'Anguilla');
insert into iso_countries (iso_code, country_name) values ('AQ', 'Antarctica');
insert into iso_countries (iso_code, country_name) values ('AG', 'Antigua and Barbuda');
insert into iso_countries (iso_code, country_name) values ('AR', 'Argentina');
insert into iso_countries (iso_code, country_name) values ('AM', 'Armenia');
insert into iso_countries (iso_code, country_name) values ('AW', 'Aruba');
insert into iso_countries (iso_code, country_name) values ('AU', 'Australia');
insert into iso_countries (iso_code, country_name) values ('AT', 'Austria');
insert into iso_countries (iso_code, country_name) values ('AZ', 'Azerbaijan');
insert into iso_countries (iso_code, country_name) values ('BS', 'Bahamas');
insert into iso_countries (iso_code, country_name) values ('BH', 'Bahrain');
insert into iso_countries (iso_code, country_name) values ('BD', 'Bangladesh');
insert into iso_countries (iso_code, country_name) values ('BB', 'Barbados');
insert into iso_countries (iso_code, country_name) values ('BY', 'Belarus');
insert into iso_countries (iso_code, country_name) values ('BE', 'Belgium');
insert into iso_countries (iso_code, country_name) values ('BZ', 'Belize');
insert into iso_countries (iso_code, country_name) values ('BJ', 'Benin');
insert into iso_countries (iso_code, country_name) values ('BM', 'Bermuda');
insert into iso_countries (iso_code, country_name) values ('BT', 'Bhutan');
insert into iso_countries (iso_code, country_name) values ('BO', 'Bolivia');
insert into iso_countries (iso_code, country_name) values ('BA', 'Bosnia and Herzegovina');
insert into iso_countries (iso_code, country_name) values ('BW', 'Botswana');
insert into iso_countries (iso_code, country_name) values ('BV', 'Bouvet Island');
insert into iso_countries (iso_code, country_name) values ('BR', 'Brazil');
insert into iso_countries (iso_code, country_name) values ('IO', 'British Indian Ocean Territory');
insert into iso_countries (iso_code, country_name) values ('BN', 'Brunei Darussalam');
insert into iso_countries (iso_code, country_name) values ('BG', 'Bulgaria');
insert into iso_countries (iso_code, country_name) values ('BF', 'Burkina Faso');
insert into iso_countries (iso_code, country_name) values ('BI', 'Burundi');
insert into iso_countries (iso_code, country_name) values ('KH', 'Cambodia');
insert into iso_countries (iso_code, country_name) values ('CM', 'Cameroon');
insert into iso_countries (iso_code, country_name) values ('CA', 'Canada');
insert into iso_countries (iso_code, country_name) values ('CV', 'Cape Verde');
insert into iso_countries (iso_code, country_name) values ('KY', 'Cayman Islands');
insert into iso_countries (iso_code, country_name) values ('CF', 'Central African Republic');
insert into iso_countries (iso_code, country_name) values ('TD', 'Chad');
insert into iso_countries (iso_code, country_name) values ('CL', 'Chile');
insert into iso_countries (iso_code, country_name) values ('CN', 'China');
insert into iso_countries (iso_code, country_name) values ('CX', 'Christmas Island');
insert into iso_countries (iso_code, country_name) values ('CC', 'Cocos (Keeling) Islands');
insert into iso_countries (iso_code, country_name) values ('CO', 'Colombia');
insert into iso_countries (iso_code, country_name) values ('KM', 'Comoros');
insert into iso_countries (iso_code, country_name) values ('CG', 'Congo');
insert into iso_countries (iso_code, country_name) values ('CD', 'Congo, the Democratic Republic of the');
insert into iso_countries (iso_code, country_name) values ('CK', 'Cook Islands');
insert into iso_countries (iso_code, country_name) values ('CR', 'Costa Rica');
insert into iso_countries (iso_code, country_name) values ('CI', 'Cote D''Ivoire');
insert into iso_countries (iso_code, country_name) values ('HR', 'Croatia');
insert into iso_countries (iso_code, country_name) values ('CU', 'Cuba');
insert into iso_countries (iso_code, country_name) values ('CY', 'Cyprus');
insert into iso_countries (iso_code, country_name) values ('CZ', 'Czech Republic');
insert into iso_countries (iso_code, country_name) values ('DK', 'Denmark');
insert into iso_countries (iso_code, country_name) values ('DJ', 'Djibouti');
insert into iso_countries (iso_code, country_name) values ('DM', 'Dominica');
insert into iso_countries (iso_code, country_name) values ('DO', 'Dominican Republic');
insert into iso_countries (iso_code, country_name) values ('EC', 'Ecuador');
insert into iso_countries (iso_code, country_name) values ('EG', 'Egypt');
insert into iso_countries (iso_code, country_name) values ('SV', 'El Salvador');
insert into iso_countries (iso_code, country_name) values ('GQ', 'Equatorial Guinea');
insert into iso_countries (iso_code, country_name) values ('ER', 'Eritrea');
insert into iso_countries (iso_code, country_name) values ('EE', 'Estonia');
insert into iso_countries (iso_code, country_name) values ('ET', 'Ethiopia');
insert into iso_countries (iso_code, country_name) values ('FK', 'Falkland Islands (Malvinas)');
insert into iso_countries (iso_code, country_name) values ('FO', 'Faroe Islands');
insert into iso_countries (iso_code, country_name) values ('FJ', 'Fiji');
insert into iso_countries (iso_code, country_name) values ('FI', 'Finland');
insert into iso_countries (iso_code, country_name) values ('FR', 'France');
insert into iso_countries (iso_code, country_name) values ('GF', 'French Guiana');
insert into iso_countries (iso_code, country_name) values ('PF', 'French Polynesia');
insert into iso_countries (iso_code, country_name) values ('TF', 'French Southern Territories');
insert into iso_countries (iso_code, country_name) values ('GA', 'Gabon');
insert into iso_countries (iso_code, country_name) values ('GM', 'Gambia');
insert into iso_countries (iso_code, country_name) values ('GE', 'Georgia');
insert into iso_countries (iso_code, country_name) values ('DE', 'Germany');
insert into iso_countries (iso_code, country_name) values ('GH', 'Ghana');
insert into iso_countries (iso_code, country_name) values ('GI', 'Gibraltar');
insert into iso_countries (iso_code, country_name) values ('GR', 'Greece');
insert into iso_countries (iso_code, country_name) values ('GL', 'Greenland');
insert into iso_countries (iso_code, country_name) values ('GD', 'Grenada');
insert into iso_countries (iso_code, country_name) values ('GP', 'Guadeloupe');
insert into iso_countries (iso_code, country_name) values ('GU', 'Guam');
insert into iso_countries (iso_code, country_name) values ('GT', 'Guatemala');
insert into iso_countries (iso_code, country_name) values ('GN', 'Guinea');
insert into iso_countries (iso_code, country_name) values ('GW', 'Guinea-Bissau');
insert into iso_countries (iso_code, country_name) values ('GY', 'Guyana');
insert into iso_countries (iso_code, country_name) values ('HT', 'Haiti');
insert into iso_countries (iso_code, country_name) values ('HM', 'Heard Island and Mcdonald Islands');
insert into iso_countries (iso_code, country_name) values ('VA', 'Holy See (Vatican City State)');
insert into iso_countries (iso_code, country_name) values ('HN', 'Honduras');
insert into iso_countries (iso_code, country_name) values ('HK', 'Hong Kong');
insert into iso_countries (iso_code, country_name) values ('HU', 'Hungary');
insert into iso_countries (iso_code, country_name) values ('IS', 'Iceland');
insert into iso_countries (iso_code, country_name) values ('IN', 'India');
insert into iso_countries (iso_code, country_name) values ('ID', 'Indonesia');
insert into iso_countries (iso_code, country_name) values ('IR', 'Iran, Islamic Republic of');
insert into iso_countries (iso_code, country_name) values ('IQ', 'Iraq');
insert into iso_countries (iso_code, country_name) values ('IE', 'Ireland');
insert into iso_countries (iso_code, country_name) values ('IL', 'Israel');
insert into iso_countries (iso_code, country_name) values ('IT', 'Italy');
insert into iso_countries (iso_code, country_name) values ('JM', 'Jamaica');
insert into iso_countries (iso_code, country_name) values ('JP', 'Japan');
insert into iso_countries (iso_code, country_name) values ('JO', 'Jordan');
insert into iso_countries (iso_code, country_name) values ('KZ', 'Kazakhstan');
insert into iso_countries (iso_code, country_name) values ('KE', 'Kenya');
insert into iso_countries (iso_code, country_name) values ('KI', 'Kiribati');
insert into iso_countries (iso_code, country_name) values ('KP', 'Korea, Democratic People''S Republic of');
insert into iso_countries (iso_code, country_name) values ('KR', 'Korea, Republic of');
insert into iso_countries (iso_code, country_name) values ('KW', 'Kuwait');
insert into iso_countries (iso_code, country_name) values ('KG', 'Kyrgyzstan');
insert into iso_countries (iso_code, country_name) values ('LA', 'Lao People''S Democratic Republic');
insert into iso_countries (iso_code, country_name) values ('LV', 'Latvia');
insert into iso_countries (iso_code, country_name) values ('LB', 'Lebanon');
insert into iso_countries (iso_code, country_name) values ('LS', 'Lesotho');
insert into iso_countries (iso_code, country_name) values ('LR', 'Liberia');
insert into iso_countries (iso_code, country_name) values ('LY', 'Libyan Arab Jamahiriya');
insert into iso_countries (iso_code, country_name) values ('LI', 'Liechtenstein');
insert into iso_countries (iso_code, country_name) values ('LT', 'Lithuania');
insert into iso_countries (iso_code, country_name) values ('LU', 'Luxembourg');
insert into iso_countries (iso_code, country_name) values ('MO', 'Macao');
insert into iso_countries (iso_code, country_name) values ('MK', 'Macedonia, the Former Yugoslav Republic of');
insert into iso_countries (iso_code, country_name) values ('MG', 'Madagascar');
insert into iso_countries (iso_code, country_name) values ('MW', 'Malawi');
insert into iso_countries (iso_code, country_name) values ('MY', 'Malaysia');
insert into iso_countries (iso_code, country_name) values ('MV', 'Maldives');
insert into iso_countries (iso_code, country_name) values ('ML', 'Mali');
insert into iso_countries (iso_code, country_name) values ('MT', 'Malta');
insert into iso_countries (iso_code, country_name) values ('MH', 'Marshall Islands');
insert into iso_countries (iso_code, country_name) values ('MQ', 'Martinique');
insert into iso_countries (iso_code, country_name) values ('MR', 'Mauritania');
insert into iso_countries (iso_code, country_name) values ('MU', 'Mauritius');
insert into iso_countries (iso_code, country_name) values ('YT', 'Mayotte');
insert into iso_countries (iso_code, country_name) values ('MX', 'Mexico');
insert into iso_countries (iso_code, country_name) values ('FM', 'Micronesia, Federated States of');
insert into iso_countries (iso_code, country_name) values ('MD', 'Moldova, Republic of');
insert into iso_countries (iso_code, country_name) values ('MC', 'Monaco');
insert into iso_countries (iso_code, country_name) values ('MN', 'Mongolia');
insert into iso_countries (iso_code, country_name) values ('MS', 'Montserrat');
insert into iso_countries (iso_code, country_name) values ('MA', 'Morocco');
insert into iso_countries (iso_code, country_name) values ('MZ', 'Mozambique');
insert into iso_countries (iso_code, country_name) values ('MM', 'Myanmar');
insert into iso_countries (iso_code, country_name) values ('NA', 'Namibia');
insert into iso_countries (iso_code, country_name) values ('NR', 'Nauru');
insert into iso_countries (iso_code, country_name) values ('NP', 'Nepal');
insert into iso_countries (iso_code, country_name) values ('NL', 'Netherlands');
insert into iso_countries (iso_code, country_name) values ('AN', 'Netherlands Antilles');
insert into iso_countries (iso_code, country_name) values ('NC', 'New Caledonia');
insert into iso_countries (iso_code, country_name) values ('NZ', 'New Zealand');
insert into iso_countries (iso_code, country_name) values ('NI', 'Nicaragua');
insert into iso_countries (iso_code, country_name) values ('NE', 'Niger');
insert into iso_countries (iso_code, country_name) values ('NG', 'Nigeria');
insert into iso_countries (iso_code, country_name) values ('NU', 'Niue');
insert into iso_countries (iso_code, country_name) values ('NF', 'Norfolk Island');
insert into iso_countries (iso_code, country_name) values ('MP', 'Northern Mariana Islands');
insert into iso_countries (iso_code, country_name) values ('NO', 'Norway');
insert into iso_countries (iso_code, country_name) values ('OM', 'Oman');
insert into iso_countries (iso_code, country_name) values ('PK', 'Pakistan');
insert into iso_countries (iso_code, country_name) values ('PW', 'Palau');
insert into iso_countries (iso_code, country_name) values ('PS', 'Palestinian Territory, Occupied');
insert into iso_countries (iso_code, country_name) values ('PA', 'Panama');
insert into iso_countries (iso_code, country_name) values ('PG', 'Papua New Guinea');
insert into iso_countries (iso_code, country_name) values ('PY', 'Paraguay');
insert into iso_countries (iso_code, country_name) values ('PE', 'Peru');
insert into iso_countries (iso_code, country_name) values ('PH', 'Philippines');
insert into iso_countries (iso_code, country_name) values ('PN', 'Pitcairn');
insert into iso_countries (iso_code, country_name) values ('PL', 'Poland');
insert into iso_countries (iso_code, country_name) values ('PT', 'Portugal');
insert into iso_countries (iso_code, country_name) values ('PR', 'Puerto Rico');
insert into iso_countries (iso_code, country_name) values ('QA', 'Qatar');
insert into iso_countries (iso_code, country_name) values ('RE', 'Reunion');
insert into iso_countries (iso_code, country_name) values ('RO', 'Romania');
insert into iso_countries (iso_code, country_name) values ('RU', 'Russian Federation');
insert into iso_countries (iso_code, country_name) values ('RW', 'Rwanda');
insert into iso_countries (iso_code, country_name) values ('SH', 'Saint Helena');
insert into iso_countries (iso_code, country_name) values ('KN', 'Saint Kitts and Nevis');
insert into iso_countries (iso_code, country_name) values ('LC', 'Saint Lucia');
insert into iso_countries (iso_code, country_name) values ('PM', 'Saint Pierre and Miquelon');
insert into iso_countries (iso_code, country_name) values ('VC', 'Saint Vincent and the Grenadines');
insert into iso_countries (iso_code, country_name) values ('WS', 'Samoa');
insert into iso_countries (iso_code, country_name) values ('SM', 'San Marino');
insert into iso_countries (iso_code, country_name) values ('ST', 'Sao Tome and Principe');
insert into iso_countries (iso_code, country_name) values ('SA', 'Saudi Arabia');
insert into iso_countries (iso_code, country_name) values ('SN', 'Senegal');
insert into iso_countries (iso_code, country_name) values ('SC', 'Seychelles');
insert into iso_countries (iso_code, country_name) values ('SL', 'Sierra Leone');
insert into iso_countries (iso_code, country_name) values ('SG', 'Singapore');
insert into iso_countries (iso_code, country_name) values ('SK', 'Slovakia');
insert into iso_countries (iso_code, country_name) values ('SI', 'Slovenia');
insert into iso_countries (iso_code, country_name) values ('SB', 'Solomon Islands');
insert into iso_countries (iso_code, country_name) values ('SO', 'Somalia');
insert into iso_countries (iso_code, country_name) values ('ZA', 'South Africa');
insert into iso_countries (iso_code, country_name) values ('GS', 'South Georgia and the South Sandwich Islands');
insert into iso_countries (iso_code, country_name) values ('ES', 'Spain');
insert into iso_countries (iso_code, country_name) values ('LK', 'Sri Lanka');
insert into iso_countries (iso_code, country_name) values ('SD', 'Sudan');
insert into iso_countries (iso_code, country_name) values ('SR', 'Suriname');
insert into iso_countries (iso_code, country_name) values ('SJ', 'Svalbard and Jan Mayen');
insert into iso_countries (iso_code, country_name) values ('SZ', 'Swaziland');
insert into iso_countries (iso_code, country_name) values ('SE', 'Sweden');
insert into iso_countries (iso_code, country_name) values ('CH', 'Switzerland');
insert into iso_countries (iso_code, country_name) values ('SY', 'Syrian Arab Republic');
insert into iso_countries (iso_code, country_name) values ('TW', 'Taiwan, Province of China');
insert into iso_countries (iso_code, country_name) values ('TJ', 'Tajikistan');
insert into iso_countries (iso_code, country_name) values ('TZ', 'Tanzania, United Republic of');
insert into iso_countries (iso_code, country_name) values ('TH', 'Thailand');
insert into iso_countries (iso_code, country_name) values ('TL', 'Timor-Leste');
insert into iso_countries (iso_code, country_name) values ('TG', 'Togo');
insert into iso_countries (iso_code, country_name) values ('TK', 'Tokelau');
insert into iso_countries (iso_code, country_name) values ('TO', 'Tonga');
insert into iso_countries (iso_code, country_name) values ('TT', 'Trinidad and Tobago');
insert into iso_countries (iso_code, country_name) values ('TN', 'Tunisia');
insert into iso_countries (iso_code, country_name) values ('TR', 'Turkey');
insert into iso_countries (iso_code, country_name) values ('TM', 'Turkmenistan');
insert into iso_countries (iso_code, country_name) values ('TC', 'Turks and Caicos Islands');
insert into iso_countries (iso_code, country_name) values ('TV', 'Tuvalu');
insert into iso_countries (iso_code, country_name) values ('UG', 'Uganda');
insert into iso_countries (iso_code, country_name) values ('UA', 'Ukraine');
insert into iso_countries (iso_code, country_name) values ('AE', 'United Arab Emirates');
insert into iso_countries (iso_code, country_name) values ('GB', 'United Kingdom');
insert into iso_countries (iso_code, country_name) values ('US', 'United States');
insert into iso_countries (iso_code, country_name) values ('UM', 'United States Minor Outlying Islands');
insert into iso_countries (iso_code, country_name) values ('UY', 'Uruguay');
insert into iso_countries (iso_code, country_name) values ('UZ', 'Uzbekistan');
insert into iso_countries (iso_code, country_name) values ('VU', 'Vanuatu');
insert into iso_countries (iso_code, country_name) values ('VE', 'Venezuela');
insert into iso_countries (iso_code, country_name) values ('VN', 'Viet Nam');
insert into iso_countries (iso_code, country_name) values ('VG', 'Virgin Islands, British');
insert into iso_countries (iso_code, country_name) values ('VI', 'Virgin Islands, U.S.');
insert into iso_countries (iso_code, country_name) values ('WF', 'Wallis and Futuna');
insert into iso_countries (iso_code, country_name) values ('EH', 'Western Sahara');
insert into iso_countries (iso_code, country_name) values ('YE', 'Yemen');
insert into iso_countries (iso_code, country_name) values ('YU', 'Yugoslavia');
insert into iso_countries (iso_code, country_name) values ('ZM', 'Zambia');
insert into iso_countries (iso_code, country_name) values ('ZW', 'Zimbabwe');
-- End
