#!/usr/bin/perl
#
#
# convert image to Encapsulated Postscript, with possible scaling of width
#

# Downloaded from http://people.redhat.com/dcm/
#
# Modified by tfox for Red Hat Documentation - default to width of 4
#

$width = "4";

if ($ARGV[0] =~ /^--width=(.+)$/) {
       $width = $1;
       shift (@ARGV);
}

#print "width =",$width,"\n";

#print "argv =",$ARGV[0],"\n";

$infile = $ARGV[0];

if (!(-e $infile)) {
print "File doesn't exist\n";
exit 1;
}

$imagesz = `identify $ARGV[0]`;

($name, $type, $size, $rest) =  split / /, $imagesz, 4;
#print "split:", $name, " ", $type, " ", $size, " ", $rest, "\n";
#print "size = ",$size,"\n";

($x, $y) = split /x/, $size, 2;
($y, $rest) = split /\+/, $y, 2;

#print $x," by ",$y, "\n";

#
# if width set, we need to scale
#

if ($width != "") {
  $scale = $width * (72.0/$x);
} else {
  $scale = 1;
}

$scale = 72.0/$scale;
#print "scale = ",$scale,"\n";

$outfile = $infile;
$outfile =~ s/\.gif/\.png/;

print $infile," ",$outfile,"\n";
system("convert -type TrueColor $infile $outfile");


